name: Compile and Test C Program

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GCC
        run: sudo apt-get install -y gcc
      - name: Set up the working directory
        run: |
        working-directory: ./Unity   
      - name: Compile C program
        run: gcc -o my_program Ctest.c

      - name: Run tests
        run: |
          if ./my_program; then
            echo "Test Passed"
          else
            echo "Test Failed"
            exit 1
          fi
      
 
