
name: Compile and Test C Program

defaults:
  run:
    shell: bash
    working-directory:  ./Unity
    
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up GCC
        run: sudo apt-get install -y gcc
    
      - name: Compile C program
        run: gcc -o my_program unity_main.c

      - name: Run tests
        run: |
          if ./my_program; then
            echo "Test Passed"
          else
            echo "Test Failed"
            exit 1
          fi
      
 
